spring.application.name=request_management

spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Setup Hibernate for H2 database
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Activate initialization via SQL scripts
spring.sql.init.mode=always

# Enable h2 console in web browser
spring.h2.console.enabled=true

# Restricts access to the H2 web console to the local machine, preventing remote connections.
spring.h2.console.settings.web-allow-others=false